# Generated by Django 4.2.20 on 2025-04-11 17:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_alter_cart_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product")},
        ),
    ]
